version: '3'

services:
  webserver:
    restart: always
    image: nginx:1.25.2
    networks: 
      - proxynet
    user: "${UID}:${GID}" # make it root first, else conf.d isn't writable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./template-variables:/etc/nginx/templates/10-variables.conf.template
      - ./certbot/www:/var/www/certbot/:ro  # for acme-challenge
      - ./certbot/conf/:/etc/nginx/ssl/:ro  # for the certificates
    env_file:
      - .env
  certbot:
    image: certbot/certbot:v2.6.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw  # The certificates are written here

networks:
  proxynet:
    name: proxynet
    driver: bridge
    ipam: 
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1
