version: '3'

services:
  webserver:
    image: nginx:1.25.2
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:v2.6.0
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw