version: '3'

services:
  webserver:
    restart: always
    image: nginx:1.25.2
    network_mode: bridge
    user: 0 # make it root first, else conf.d isn't writable
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/simple-proxy/:/etc/nginx/conf.d/
      - ./template-variables:/etc/nginx/templates/10-variables.conf.template


# Run in Default Bridge Network
# https://faun.pub/run-the-containers-in-default-bridge-network-with-docker-compose-yml-f8e57590722